server:
  port: 2026

spring:
  mvc:
    # 如果你把前端静态文件放在 resources/static 下，这个保持默认即可
    static-path-pattern: "/**"
  application:
    name: krl-web  # 对应spring.application.name
  servlet:
    multipart:
      max-file-size: 100MB    # 单个文件最大大小
      max-request-size: 1000MB # 单次请求最大大小（包含所有文件）

logging:
  file:
    # 设定日志存储的目录和文件名
    name: logs/krl-analysis.log
  logback:
    rollingpolicy:
      # 设置日志保留策略，防止磁盘满
      max-file-size: 10MB
      max-history: 7
  level:
    root: INFO
    # 如果你想看更详细的 Spring 启动过程，可以设为 DEBUG
    org.springframework: INFO